server:
  port: 8761

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:    
    enableSelfPreservation: false
    eviction-interval-timer-in-ms: 500
    response-cache-update-interval-ms: 500
